### ISSUE TITLE
Please update qr package

### ISSUE THREAD

**Issue by IbrahimAlqayyas** [theyakka/qr.flutter#178]
**Describe the bug**
Please update the qr package to v3.0.0 or higher because the package is making conflicts with other packages like the PDF package when i use them with each others.

**Comment by Guthers** [comment]
I am not in a position to the PR itself. I have however got the current "working versions" of the packages below. Hopefully it saves someone else a little bit of time

```yaml
qr_flutter: ^4.0.0
pdf: ^3.6.4
printing: ^5.6.5
```
